# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odmactor_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OdmactorMainWindow(object):
    def setupUi(self, OdmactorMainWindow):
        OdmactorMainWindow.setObjectName("OdmactorMainWindow")
        OdmactorMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(OdmactorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        OdmactorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OdmactorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        OdmactorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OdmactorMainWindow)
        self.statusbar.setObjectName("statusbar")
        OdmactorMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OdmactorMainWindow)
        QtCore.QMetaObject.connectSlotsByName(OdmactorMainWindow)

    def retranslateUi(self, OdmactorMainWindow):
        _translate = QtCore.QCoreApplication.translate
        OdmactorMainWindow.setWindowTitle(_translate("OdmactorMainWindow", "ODMACTOR"))
