# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odmactor_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OdmactorMainWindow(object):
    def setupUi(self, OdmactorMainWindow):
        OdmactorMainWindow.setObjectName("OdmactorMainWindow")
        OdmactorMainWindow.resize(1512, 1188)
        self.centralwidget = QtWidgets.QWidget(OdmactorMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.toolBox = QtWidgets.QToolBox(self.splitter)
        self.toolBox.setEnabled(True)
        self.toolBox.setMinimumSize(QtCore.QSize(420, 0))
        self.toolBox.setObjectName("toolBox")
        self.pageGeneric = QtWidgets.QWidget()
        self.pageGeneric.setGeometry(QtCore.QRect(0, 0, 517, 1025))
        self.pageGeneric.setObjectName("pageGeneric")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.pageGeneric)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.groupBoxMicrowaveControl = QtWidgets.QGroupBox(self.pageGeneric)
        self.groupBoxMicrowaveControl.setObjectName("groupBoxMicrowaveControl")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBoxMicrowaveControl)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelMicrowaveFrequency = QtWidgets.QLabel(self.groupBoxMicrowaveControl)
        self.labelMicrowaveFrequency.setObjectName("labelMicrowaveFrequency")
        self.horizontalLayout_6.addWidget(self.labelMicrowaveFrequency)
        self.doubleSpinBoxMicrowaveFrequency = QtWidgets.QDoubleSpinBox(self.groupBoxMicrowaveControl)
        self.doubleSpinBoxMicrowaveFrequency.setMaximum(999.0)
        self.doubleSpinBoxMicrowaveFrequency.setProperty("value", 1.0)
        self.doubleSpinBoxMicrowaveFrequency.setObjectName("doubleSpinBoxMicrowaveFrequency")
        self.horizontalLayout_6.addWidget(self.doubleSpinBoxMicrowaveFrequency)
        self.comboBoxMicrowaveFrequencyUnit = QtWidgets.QComboBox(self.groupBoxMicrowaveControl)
        self.comboBoxMicrowaveFrequencyUnit.setObjectName("comboBoxMicrowaveFrequencyUnit")
        self.comboBoxMicrowaveFrequencyUnit.addItem("")
        self.comboBoxMicrowaveFrequencyUnit.addItem("")
        self.comboBoxMicrowaveFrequencyUnit.addItem("")
        self.comboBoxMicrowaveFrequencyUnit.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBoxMicrowaveFrequencyUnit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.labelMicrowavePower = QtWidgets.QLabel(self.groupBoxMicrowaveControl)
        self.labelMicrowavePower.setObjectName("labelMicrowavePower")
        self.horizontalLayout_7.addWidget(self.labelMicrowavePower)
        self.doubleSpinBoxMicrowavePower = QtWidgets.QDoubleSpinBox(self.groupBoxMicrowaveControl)
        self.doubleSpinBoxMicrowavePower.setSuffix("")
        self.doubleSpinBoxMicrowavePower.setMinimum(-50.0)
        self.doubleSpinBoxMicrowavePower.setMaximum(30.0)
        self.doubleSpinBoxMicrowavePower.setObjectName("doubleSpinBoxMicrowavePower")
        self.horizontalLayout_7.addWidget(self.doubleSpinBoxMicrowavePower)
        self.comboBoxMicrowavePowerUnit = QtWidgets.QComboBox(self.groupBoxMicrowaveControl)
        self.comboBoxMicrowavePowerUnit.setObjectName("comboBoxMicrowavePowerUnit")
        self.comboBoxMicrowavePowerUnit.addItem("")
        self.comboBoxMicrowavePowerUnit.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBoxMicrowavePowerUnit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButtonMicrowaveOnOff = QtWidgets.QPushButton(self.groupBoxMicrowaveControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMicrowaveOnOff.sizePolicy().hasHeightForWidth())
        self.pushButtonMicrowaveOnOff.setSizePolicy(sizePolicy)
        self.pushButtonMicrowaveOnOff.setCheckable(True)
        self.pushButtonMicrowaveOnOff.setObjectName("pushButtonMicrowaveOnOff")
        self.horizontalLayout_21.addWidget(self.pushButtonMicrowaveOnOff)
        self.pushButtonMicrowaveConnect = QtWidgets.QPushButton(self.groupBoxMicrowaveControl)
        self.pushButtonMicrowaveConnect.setObjectName("pushButtonMicrowaveConnect")
        self.horizontalLayout_21.addWidget(self.pushButtonMicrowaveConnect)
        self.pushButtonMicrowaveClose = QtWidgets.QPushButton(self.groupBoxMicrowaveControl)
        self.pushButtonMicrowaveClose.setObjectName("pushButtonMicrowaveClose")
        self.horizontalLayout_21.addWidget(self.pushButtonMicrowaveClose)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.groupBoxMicrowaveTimer = QtWidgets.QGroupBox(self.groupBoxMicrowaveControl)
        self.groupBoxMicrowaveTimer.setCheckable(True)
        self.groupBoxMicrowaveTimer.setChecked(False)
        self.groupBoxMicrowaveTimer.setObjectName("groupBoxMicrowaveTimer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBoxMicrowaveTimer)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelMicrowaveTimer = QtWidgets.QLabel(self.groupBoxMicrowaveTimer)
        self.labelMicrowaveTimer.setObjectName("labelMicrowaveTimer")
        self.horizontalLayout_4.addWidget(self.labelMicrowaveTimer)
        self.doubleSpinBoxMicrowaveTimerTime = QtWidgets.QDoubleSpinBox(self.groupBoxMicrowaveTimer)
        self.doubleSpinBoxMicrowaveTimerTime.setObjectName("doubleSpinBoxMicrowaveTimerTime")
        self.horizontalLayout_4.addWidget(self.doubleSpinBoxMicrowaveTimerTime)
        self.comboBoxMicrowaveTimerTimeUnit = QtWidgets.QComboBox(self.groupBoxMicrowaveTimer)
        self.comboBoxMicrowaveTimerTimeUnit.setObjectName("comboBoxMicrowaveTimerTimeUnit")
        self.comboBoxMicrowaveTimerTimeUnit.addItem("")
        self.comboBoxMicrowaveTimerTimeUnit.addItem("")
        self.comboBoxMicrowaveTimerTimeUnit.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBoxMicrowaveTimerTimeUnit)
        self.verticalLayout_7.addWidget(self.groupBoxMicrowaveTimer)
        self.groupBoxMicrowavePiPulse = QtWidgets.QGroupBox(self.groupBoxMicrowaveControl)
        self.groupBoxMicrowavePiPulse.setObjectName("groupBoxMicrowavePiPulse")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBoxMicrowavePiPulse)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelMicrowavePiPulsePiPulseFrequency = QtWidgets.QLabel(self.groupBoxMicrowavePiPulse)
        self.labelMicrowavePiPulsePiPulseFrequency.setObjectName("labelMicrowavePiPulsePiPulseFrequency")
        self.horizontalLayout_5.addWidget(self.labelMicrowavePiPulsePiPulseFrequency)
        self.doubleSpinBoxMicrowavePiPulseFrequency = QtWidgets.QDoubleSpinBox(self.groupBoxMicrowavePiPulse)
        self.doubleSpinBoxMicrowavePiPulseFrequency.setMaximum(999.99)
        self.doubleSpinBoxMicrowavePiPulseFrequency.setObjectName("doubleSpinBoxMicrowavePiPulseFrequency")
        self.horizontalLayout_5.addWidget(self.doubleSpinBoxMicrowavePiPulseFrequency)
        self.comboBoxMicrowavePiPulseFrequencyUnit = QtWidgets.QComboBox(self.groupBoxMicrowavePiPulse)
        self.comboBoxMicrowavePiPulseFrequencyUnit.setObjectName("comboBoxMicrowavePiPulseFrequencyUnit")
        self.comboBoxMicrowavePiPulseFrequencyUnit.addItem("")
        self.comboBoxMicrowavePiPulseFrequencyUnit.addItem("")
        self.comboBoxMicrowavePiPulseFrequencyUnit.addItem("")
        self.comboBoxMicrowavePiPulseFrequencyUnit.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBoxMicrowavePiPulseFrequencyUnit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.labelMicrowavePiPulseDuration = QtWidgets.QLabel(self.groupBoxMicrowavePiPulse)
        self.labelMicrowavePiPulseDuration.setObjectName("labelMicrowavePiPulseDuration")
        self.horizontalLayout_20.addWidget(self.labelMicrowavePiPulseDuration)
        self.doubleSpinBoxMicrowavePiPulseDuration = QtWidgets.QDoubleSpinBox(self.groupBoxMicrowavePiPulse)
        self.doubleSpinBoxMicrowavePiPulseDuration.setMaximum(999.99)
        self.doubleSpinBoxMicrowavePiPulseDuration.setObjectName("doubleSpinBoxMicrowavePiPulseDuration")
        self.horizontalLayout_20.addWidget(self.doubleSpinBoxMicrowavePiPulseDuration)
        self.comboBoxMicrowavePiPulseDurationUnit = QtWidgets.QComboBox(self.groupBoxMicrowavePiPulse)
        self.comboBoxMicrowavePiPulseDurationUnit.setObjectName("comboBoxMicrowavePiPulseDurationUnit")
        self.comboBoxMicrowavePiPulseDurationUnit.addItem("")
        self.comboBoxMicrowavePiPulseDurationUnit.addItem("")
        self.comboBoxMicrowavePiPulseDurationUnit.addItem("")
        self.horizontalLayout_20.addWidget(self.comboBoxMicrowavePiPulseDurationUnit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.labelMicrowavePiPulsePower = QtWidgets.QLabel(self.groupBoxMicrowavePiPulse)
        self.labelMicrowavePiPulsePower.setObjectName("labelMicrowavePiPulsePower")
        self.horizontalLayout_19.addWidget(self.labelMicrowavePiPulsePower)
        self.doubleSpinBoxMicrowavePiPulsePower = QtWidgets.QDoubleSpinBox(self.groupBoxMicrowavePiPulse)
        self.doubleSpinBoxMicrowavePiPulsePower.setMinimum(-50.0)
        self.doubleSpinBoxMicrowavePiPulsePower.setMaximum(30.0)
        self.doubleSpinBoxMicrowavePiPulsePower.setObjectName("doubleSpinBoxMicrowavePiPulsePower")
        self.horizontalLayout_19.addWidget(self.doubleSpinBoxMicrowavePiPulsePower)
        self.comboBoxMicrowavePiPulsePowerUnit = QtWidgets.QComboBox(self.groupBoxMicrowavePiPulse)
        self.comboBoxMicrowavePiPulsePowerUnit.setObjectName("comboBoxMicrowavePiPulsePowerUnit")
        self.comboBoxMicrowavePiPulsePowerUnit.addItem("")
        self.comboBoxMicrowavePiPulsePowerUnit.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBoxMicrowavePiPulsePowerUnit)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.verticalLayout_7.addWidget(self.groupBoxMicrowavePiPulse)
        self.gridLayout_12.addWidget(self.groupBoxMicrowaveControl, 0, 0, 1, 1)
        self.groupBoxLaserControl = QtWidgets.QGroupBox(self.pageGeneric)
        self.groupBoxLaserControl.setObjectName("groupBoxLaserControl")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxLaserControl)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.radioButtonLaserCW = QtWidgets.QRadioButton(self.groupBoxLaserControl)
        self.radioButtonLaserCW.setObjectName("radioButtonLaserCW")
        self.gridLayout_7.addWidget(self.radioButtonLaserCW, 0, 0, 1, 1)
        self.radioButtonLaserPulse = QtWidgets.QRadioButton(self.groupBoxLaserControl)
        self.radioButtonLaserPulse.setObjectName("radioButtonLaserPulse")
        self.gridLayout_7.addWidget(self.radioButtonLaserPulse, 0, 1, 1, 1)
        self.pushButtonLaserOnOff = QtWidgets.QPushButton(self.groupBoxLaserControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLaserOnOff.sizePolicy().hasHeightForWidth())
        self.pushButtonLaserOnOff.setSizePolicy(sizePolicy)
        self.pushButtonLaserOnOff.setCheckable(True)
        self.pushButtonLaserOnOff.setObjectName("pushButtonLaserOnOff")
        self.gridLayout_7.addWidget(self.pushButtonLaserOnOff, 0, 2, 1, 2)
        self.labelLaserPower = QtWidgets.QLabel(self.groupBoxLaserControl)
        self.labelLaserPower.setObjectName("labelLaserPower")
        self.gridLayout_7.addWidget(self.labelLaserPower, 1, 0, 1, 1)
        self.doubleSpinBoxLaserPower = QtWidgets.QDoubleSpinBox(self.groupBoxLaserControl)
        self.doubleSpinBoxLaserPower.setObjectName("doubleSpinBoxLaserPower")
        self.gridLayout_7.addWidget(self.doubleSpinBoxLaserPower, 1, 1, 1, 1)
        self.pushButtonLaserConnect = QtWidgets.QPushButton(self.groupBoxLaserControl)
        self.pushButtonLaserConnect.setObjectName("pushButtonLaserConnect")
        self.gridLayout_7.addWidget(self.pushButtonLaserConnect, 1, 2, 1, 1)
        self.pushButtonLaserClose = QtWidgets.QPushButton(self.groupBoxLaserControl)
        self.pushButtonLaserClose.setObjectName("pushButtonLaserClose")
        self.gridLayout_7.addWidget(self.pushButtonLaserClose, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        self.label_2 = QtWidgets.QLabel(self.groupBoxLaserControl)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.gridLayout_12.addWidget(self.groupBoxLaserControl, 1, 0, 1, 1)
        self.groupBoxASGChannels = QtWidgets.QGroupBox(self.pageGeneric)
        self.groupBoxASGChannels.setObjectName("groupBoxASGChannels")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBoxASGChannels)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.labelHistType = QtWidgets.QLabel(self.groupBoxASGChannels)
        self.labelHistType.setObjectName("labelHistType")
        self.gridLayout_18.addWidget(self.labelHistType, 0, 0, 1, 1)
        self.labelSplit = QtWidgets.QLabel(self.groupBoxASGChannels)
        self.labelSplit.setObjectName("labelSplit")
        self.gridLayout_18.addWidget(self.labelSplit, 1, 0, 1, 1)
        self.comboBoxASGLaser = QtWidgets.QComboBox(self.groupBoxASGChannels)
        self.comboBoxASGLaser.setObjectName("comboBoxASGLaser")
        self.comboBoxASGLaser.addItem("")
        self.comboBoxASGLaser.addItem("")
        self.comboBoxASGLaser.addItem("")
        self.comboBoxASGLaser.addItem("")
        self.comboBoxASGLaser.addItem("")
        self.comboBoxASGLaser.addItem("")
        self.comboBoxASGLaser.addItem("")
        self.comboBoxASGLaser.addItem("")
        self.gridLayout_18.addWidget(self.comboBoxASGLaser, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBoxASGChannels)
        self.label_12.setObjectName("label_12")
        self.gridLayout_18.addWidget(self.label_12, 4, 0, 1, 1)
        self.comboBoxASGTagger = QtWidgets.QComboBox(self.groupBoxASGChannels)
        self.comboBoxASGTagger.setObjectName("comboBoxASGTagger")
        self.comboBoxASGTagger.addItem("")
        self.comboBoxASGTagger.addItem("")
        self.comboBoxASGTagger.addItem("")
        self.comboBoxASGTagger.addItem("")
        self.comboBoxASGTagger.addItem("")
        self.comboBoxASGTagger.addItem("")
        self.comboBoxASGTagger.addItem("")
        self.comboBoxASGTagger.addItem("")
        self.gridLayout_18.addWidget(self.comboBoxASGTagger, 4, 1, 1, 1)
        self.comboBoxASGAPD = QtWidgets.QComboBox(self.groupBoxASGChannels)
        self.comboBoxASGAPD.setObjectName("comboBoxASGAPD")
        self.comboBoxASGAPD.addItem("")
        self.comboBoxASGAPD.addItem("")
        self.comboBoxASGAPD.addItem("")
        self.comboBoxASGAPD.addItem("")
        self.comboBoxASGAPD.addItem("")
        self.comboBoxASGAPD.addItem("")
        self.comboBoxASGAPD.addItem("")
        self.comboBoxASGAPD.addItem("")
        self.gridLayout_18.addWidget(self.comboBoxASGAPD, 3, 1, 1, 1)
        self.comboBoxASGMicrowave = QtWidgets.QComboBox(self.groupBoxASGChannels)
        self.comboBoxASGMicrowave.setObjectName("comboBoxASGMicrowave")
        self.comboBoxASGMicrowave.addItem("")
        self.comboBoxASGMicrowave.addItem("")
        self.comboBoxASGMicrowave.addItem("")
        self.comboBoxASGMicrowave.addItem("")
        self.comboBoxASGMicrowave.addItem("")
        self.comboBoxASGMicrowave.addItem("")
        self.comboBoxASGMicrowave.addItem("")
        self.comboBoxASGMicrowave.addItem("")
        self.gridLayout_18.addWidget(self.comboBoxASGMicrowave, 1, 1, 1, 1)
        self.checkBoxASGLaserTTL = QtWidgets.QCheckBox(self.groupBoxASGChannels)
        self.checkBoxASGLaserTTL.setChecked(True)
        self.checkBoxASGLaserTTL.setObjectName("checkBoxASGLaserTTL")
        self.gridLayout_18.addWidget(self.checkBoxASGLaserTTL, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBoxASGChannels)
        self.label_11.setObjectName("label_11")
        self.gridLayout_18.addWidget(self.label_11, 3, 0, 1, 1)
        self.checkBoxASGTaggerTTL = QtWidgets.QCheckBox(self.groupBoxASGChannels)
        self.checkBoxASGTaggerTTL.setChecked(True)
        self.checkBoxASGTaggerTTL.setObjectName("checkBoxASGTaggerTTL")
        self.gridLayout_18.addWidget(self.checkBoxASGTaggerTTL, 4, 2, 1, 1)
        self.checkBoxASGMicrowaveTTL = QtWidgets.QCheckBox(self.groupBoxASGChannels)
        self.checkBoxASGMicrowaveTTL.setChecked(True)
        self.checkBoxASGMicrowaveTTL.setObjectName("checkBoxASGMicrowaveTTL")
        self.gridLayout_18.addWidget(self.checkBoxASGMicrowaveTTL, 1, 2, 1, 1)
        self.checkBoxASGAPDTTL = QtWidgets.QCheckBox(self.groupBoxASGChannels)
        self.checkBoxASGAPDTTL.setChecked(True)
        self.checkBoxASGAPDTTL.setObjectName("checkBoxASGAPDTTL")
        self.gridLayout_18.addWidget(self.checkBoxASGAPDTTL, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBoxASGChannels)
        self.label.setObjectName("label")
        self.gridLayout_18.addWidget(self.label, 2, 0, 1, 1)
        self.checkBoxASGMicrowaveSync = QtWidgets.QCheckBox(self.groupBoxASGChannels)
        self.checkBoxASGMicrowaveSync.setEnabled(False)
        self.checkBoxASGMicrowaveSync.setChecked(True)
        self.checkBoxASGMicrowaveSync.setObjectName("checkBoxASGMicrowaveSync")
        self.gridLayout_18.addWidget(self.checkBoxASGMicrowaveSync, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBoxASGChannels)
        self.label_4.setObjectName("label_4")
        self.gridLayout_18.addWidget(self.label_4, 5, 0, 1, 1)
        self.checkBoxASGLockinSyncTTL = QtWidgets.QCheckBox(self.groupBoxASGChannels)
        self.checkBoxASGLockinSyncTTL.setEnabled(False)
        self.checkBoxASGLockinSyncTTL.setChecked(True)
        self.checkBoxASGLockinSyncTTL.setObjectName("checkBoxASGLockinSyncTTL")
        self.gridLayout_18.addWidget(self.checkBoxASGLockinSyncTTL, 5, 2, 1, 1)
        self.comboBoxASGLockinSync = QtWidgets.QComboBox(self.groupBoxASGChannels)
        self.comboBoxASGLockinSync.setObjectName("comboBoxASGLockinSync")
        self.comboBoxASGLockinSync.addItem("")
        self.comboBoxASGLockinSync.addItem("")
        self.comboBoxASGLockinSync.addItem("")
        self.comboBoxASGLockinSync.addItem("")
        self.comboBoxASGLockinSync.addItem("")
        self.comboBoxASGLockinSync.addItem("")
        self.comboBoxASGLockinSync.addItem("")
        self.comboBoxASGLockinSync.addItem("")
        self.gridLayout_18.addWidget(self.comboBoxASGLockinSync, 5, 1, 1, 1)
        self.comboBoxASGMicrowaveSync = QtWidgets.QComboBox(self.groupBoxASGChannels)
        self.comboBoxASGMicrowaveSync.setObjectName("comboBoxASGMicrowaveSync")
        self.comboBoxASGMicrowaveSync.addItem("")
        self.comboBoxASGMicrowaveSync.addItem("")
        self.comboBoxASGMicrowaveSync.addItem("")
        self.comboBoxASGMicrowaveSync.addItem("")
        self.comboBoxASGMicrowaveSync.addItem("")
        self.comboBoxASGMicrowaveSync.addItem("")
        self.comboBoxASGMicrowaveSync.addItem("")
        self.comboBoxASGMicrowaveSync.addItem("")
        self.gridLayout_18.addWidget(self.comboBoxASGMicrowaveSync, 2, 1, 1, 1)
        self.gridLayout_12.addWidget(self.groupBoxASGChannels, 2, 0, 1, 1)
        self.groupBoxTaggerChannels = QtWidgets.QGroupBox(self.pageGeneric)
        self.groupBoxTaggerChannels.setObjectName("groupBoxTaggerChannels")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxTaggerChannels)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButtonUseTagger = QtWidgets.QRadioButton(self.groupBoxTaggerChannels)
        self.radioButtonUseTagger.setObjectName("radioButtonUseTagger")
        self.gridLayout_2.addWidget(self.radioButtonUseTagger, 0, 2, 1, 1)
        self.comboBoxTaggerAPD = QtWidgets.QComboBox(self.groupBoxTaggerChannels)
        self.comboBoxTaggerAPD.setObjectName("comboBoxTaggerAPD")
        self.comboBoxTaggerAPD.addItem("")
        self.comboBoxTaggerAPD.addItem("")
        self.comboBoxTaggerAPD.addItem("")
        self.comboBoxTaggerAPD.addItem("")
        self.comboBoxTaggerAPD.addItem("")
        self.comboBoxTaggerAPD.addItem("")
        self.comboBoxTaggerAPD.addItem("")
        self.comboBoxTaggerAPD.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxTaggerAPD, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBoxTaggerChannels)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.comboBoxTaggerTrigger = QtWidgets.QComboBox(self.groupBoxTaggerChannels)
        self.comboBoxTaggerTrigger.setObjectName("comboBoxTaggerTrigger")
        self.comboBoxTaggerTrigger.addItem("")
        self.comboBoxTaggerTrigger.addItem("")
        self.comboBoxTaggerTrigger.addItem("")
        self.comboBoxTaggerTrigger.addItem("")
        self.comboBoxTaggerTrigger.addItem("")
        self.comboBoxTaggerTrigger.addItem("")
        self.comboBoxTaggerTrigger.addItem("")
        self.comboBoxTaggerTrigger.addItem("")
        self.gridLayout_2.addWidget(self.comboBoxTaggerTrigger, 1, 1, 1, 1)
        self.radioButtonUseLockin = QtWidgets.QRadioButton(self.groupBoxTaggerChannels)
        self.radioButtonUseLockin.setChecked(True)
        self.radioButtonUseLockin.setObjectName("radioButtonUseLockin")
        self.gridLayout_2.addWidget(self.radioButtonUseLockin, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBoxTaggerChannels)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBoxTaggerChannels, 3, 0, 1, 1)
        self.toolBox.addItem(self.pageGeneric, "")
        self.pageODMR = QtWidgets.QWidget()
        self.pageODMR.setGeometry(QtCore.QRect(0, 0, 517, 1025))
        self.pageODMR.setObjectName("pageODMR")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pageODMR)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxODMROperation = QtWidgets.QGroupBox(self.pageODMR)
        self.groupBoxODMROperation.setObjectName("groupBoxODMROperation")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBoxODMROperation)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButtonODMRLoadSequences = QtWidgets.QPushButton(self.groupBoxODMROperation)
        self.pushButtonODMRLoadSequences.setObjectName("pushButtonODMRLoadSequences")
        self.horizontalLayout_9.addWidget(self.pushButtonODMRLoadSequences)
        self.pushButtonODMRStartDetecting = QtWidgets.QPushButton(self.groupBoxODMROperation)
        self.pushButtonODMRStartDetecting.setObjectName("pushButtonODMRStartDetecting")
        self.horizontalLayout_9.addWidget(self.pushButtonODMRStartDetecting)
        self.pushButtonODMRSaveData = QtWidgets.QPushButton(self.groupBoxODMROperation)
        self.pushButtonODMRSaveData.setObjectName("pushButtonODMRSaveData")
        self.horizontalLayout_9.addWidget(self.pushButtonODMRSaveData)
        self.verticalLayout.addWidget(self.groupBoxODMROperation)
        self.groupBoxODMRFrequency = QtWidgets.QGroupBox(self.pageODMR)
        self.groupBoxODMRFrequency.setCheckable(True)
        self.groupBoxODMRFrequency.setObjectName("groupBoxODMRFrequency")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBoxODMRFrequency)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBoxODMRFrequency)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.radioButtonODMRCW = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButtonODMRCW.setChecked(True)
        self.radioButtonODMRCW.setObjectName("radioButtonODMRCW")
        self.horizontalLayout_15.addWidget(self.radioButtonODMRCW)
        self.radioButtonODMRPulse = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButtonODMRPulse.setObjectName("radioButtonODMRPulse")
        self.horizontalLayout_15.addWidget(self.radioButtonODMRPulse)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBoxODMRFrequencyScanning = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBoxODMRFrequencyScanning.setChecked(True)
        self.checkBoxODMRFrequencyScanning.setObjectName("checkBoxODMRFrequencyScanning")
        self.horizontalLayout_14.addWidget(self.checkBoxODMRFrequencyScanning)
        self.label_34 = QtWidgets.QLabel(self.groupBox_10)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_14.addWidget(self.label_34)
        self.comboBoxODMRFrequencyUnit = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBoxODMRFrequencyUnit.setObjectName("comboBoxODMRFrequencyUnit")
        self.comboBoxODMRFrequencyUnit.addItem("")
        self.comboBoxODMRFrequencyUnit.addItem("")
        self.comboBoxODMRFrequencyUnit.addItem("")
        self.comboBoxODMRFrequencyUnit.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBoxODMRFrequencyUnit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_10)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_16.addWidget(self.label_17)
        self.doubleSpinBoxODMRFrequencyStart = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBoxODMRFrequencyStart.setMaximum(1000.0)
        self.doubleSpinBoxODMRFrequencyStart.setObjectName("doubleSpinBoxODMRFrequencyStart")
        self.horizontalLayout_16.addWidget(self.doubleSpinBoxODMRFrequencyStart)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_10)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_17.addWidget(self.label_18)
        self.doubleSpinBoxODMRFrequencyEnd = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBoxODMRFrequencyEnd.setMaximum(1000.0)
        self.doubleSpinBoxODMRFrequencyEnd.setObjectName("doubleSpinBoxODMRFrequencyEnd")
        self.horizontalLayout_17.addWidget(self.doubleSpinBoxODMRFrequencyEnd)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.doubleSpinBoxODMRFrequencyStep = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.doubleSpinBoxODMRFrequencyStep.setMaximum(1000.0)
        self.doubleSpinBoxODMRFrequencyStep.setObjectName("doubleSpinBoxODMRFrequencyStep")
        self.horizontalLayout_18.addWidget(self.doubleSpinBoxODMRFrequencyStep)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        self.gridLayout_6.addWidget(self.groupBox_10, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBoxODMRFrequency)
        self.groupBoxODMRTime = QtWidgets.QGroupBox(self.pageODMR)
        self.groupBoxODMRTime.setCheckable(True)
        self.groupBoxODMRTime.setChecked(False)
        self.groupBoxODMRTime.setObjectName("groupBoxODMRTime")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBoxODMRTime)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBoxODMRTime)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButtonODMRRabi = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButtonODMRRabi.setObjectName("radioButtonODMRRabi")
        self.horizontalLayout_8.addWidget(self.radioButtonODMRRabi)
        self.radioButtonODMRRamsey = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButtonODMRRamsey.setObjectName("radioButtonODMRRamsey")
        self.horizontalLayout_8.addWidget(self.radioButtonODMRRamsey)
        self.radioButtonPulseODMRRelaxation = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButtonPulseODMRRelaxation.setObjectName("radioButtonPulseODMRRelaxation")
        self.horizontalLayout_8.addWidget(self.radioButtonPulseODMRRelaxation)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBoxODMRTimeScanning = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBoxODMRTimeScanning.setChecked(True)
        self.checkBoxODMRTimeScanning.setObjectName("checkBoxODMRTimeScanning")
        self.horizontalLayout_13.addWidget(self.checkBoxODMRTimeScanning)
        self.label_32 = QtWidgets.QLabel(self.groupBox_12)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_13.addWidget(self.label_32)
        self.comboBoxODMRTimeUnit = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBoxODMRTimeUnit.setObjectName("comboBoxODMRTimeUnit")
        self.comboBoxODMRTimeUnit.addItem("")
        self.comboBoxODMRTimeUnit.addItem("")
        self.comboBoxODMRTimeUnit.addItem("")
        self.comboBoxODMRTimeUnit.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBoxODMRTimeUnit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_30 = QtWidgets.QLabel(self.groupBox_12)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_10.addWidget(self.label_30)
        self.doubleSpinBoxODMRTimeStart = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.doubleSpinBoxODMRTimeStart.setMaximum(1000.0)
        self.doubleSpinBoxODMRTimeStart.setObjectName("doubleSpinBoxODMRTimeStart")
        self.horizontalLayout_10.addWidget(self.doubleSpinBoxODMRTimeStart)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_31 = QtWidgets.QLabel(self.groupBox_12)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_11.addWidget(self.label_31)
        self.doubleSpinBoxODMRTimeEnd = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.doubleSpinBoxODMRTimeEnd.setMaximum(1000.0)
        self.doubleSpinBoxODMRTimeEnd.setObjectName("doubleSpinBoxODMRTimeEnd")
        self.horizontalLayout_11.addWidget(self.doubleSpinBoxODMRTimeEnd)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_33 = QtWidgets.QLabel(self.groupBox_12)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_12.addWidget(self.label_33)
        self.doubleSpinBoxODMRTimeStep = QtWidgets.QDoubleSpinBox(self.groupBox_12)
        self.doubleSpinBoxODMRTimeStep.setMaximum(1000.0)
        self.doubleSpinBoxODMRTimeStep.setObjectName("doubleSpinBoxODMRTimeStep")
        self.horizontalLayout_12.addWidget(self.doubleSpinBoxODMRTimeStep)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_35 = QtWidgets.QLabel(self.groupBox_12)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_22.addWidget(self.label_35)
        self.spinBoxODMRTimeLength = QtWidgets.QSpinBox(self.groupBox_12)
        self.spinBoxODMRTimeLength.setMaximum(102)
        self.spinBoxODMRTimeLength.setObjectName("spinBoxODMRTimeLength")
        self.horizontalLayout_22.addWidget(self.spinBoxODMRTimeLength)
        self.verticalLayout_5.addLayout(self.horizontalLayout_22)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.radioButtonODMRTimeUseStep = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonODMRTimeUseStep.setChecked(True)
        self.radioButtonODMRTimeUseStep.setObjectName("radioButtonODMRTimeUseStep")
        self.horizontalLayout_23.addWidget(self.radioButtonODMRTimeUseStep)
        self.radioButtonODMRTimeUseLength = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonODMRTimeUseLength.setObjectName("radioButtonODMRTimeUseLength")
        self.horizontalLayout_23.addWidget(self.radioButtonODMRTimeUseLength)
        self.radioButtonODMRTimeUseLengthAndLogarithm = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonODMRTimeUseLengthAndLogarithm.setObjectName("radioButtonODMRTimeUseLengthAndLogarithm")
        self.horizontalLayout_23.addWidget(self.radioButtonODMRTimeUseLengthAndLogarithm)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_4.addWidget(self.groupBox_12)
        self.verticalLayout.addWidget(self.groupBoxODMRTime)
        self.groupBoxODMRSequenceConfiguration = QtWidgets.QGroupBox(self.pageODMR)
        self.groupBoxODMRSequenceConfiguration.setObjectName("groupBoxODMRSequenceConfiguration")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBoxODMRSequenceConfiguration)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.spinBoxODMRMicrowaveReadoutInterval = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRMicrowaveReadoutInterval.setMaximum(100000)
        self.spinBoxODMRMicrowaveReadoutInterval.setSingleStep(10)
        self.spinBoxODMRMicrowaveReadoutInterval.setObjectName("spinBoxODMRMicrowaveReadoutInterval")
        self.gridLayout_11.addWidget(self.spinBoxODMRMicrowaveReadoutInterval, 10, 1, 1, 1)
        self.spinBoxODMRPreReadoutInterval = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRPreReadoutInterval.setMaximum(100000)
        self.spinBoxODMRPreReadoutInterval.setSingleStep(10)
        self.spinBoxODMRPreReadoutInterval.setObjectName("spinBoxODMRPreReadoutInterval")
        self.gridLayout_11.addWidget(self.spinBoxODMRPreReadoutInterval, 11, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 11, 0, 1, 1)
        self.spinBoxODMRPeriodNumber = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRPeriodNumber.setMinimum(100)
        self.spinBoxODMRPeriodNumber.setMaximum(10000000)
        self.spinBoxODMRPeriodNumber.setSingleStep(100)
        self.spinBoxODMRPeriodNumber.setObjectName("spinBoxODMRPeriodNumber")
        self.gridLayout_11.addWidget(self.spinBoxODMRPeriodNumber, 1, 1, 1, 1)
        self.spinBoxODMRSignalReadoutTime = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRSignalReadoutTime.setMaximum(100000)
        self.spinBoxODMRSignalReadoutTime.setSingleStep(10)
        self.spinBoxODMRSignalReadoutTime.setObjectName("spinBoxODMRSignalReadoutTime")
        self.gridLayout_11.addWidget(self.spinBoxODMRSignalReadoutTime, 14, 1, 1, 1)
        self.spinBoxODMRMicrowaveTime = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRMicrowaveTime.setMaximum(100000)
        self.spinBoxODMRMicrowaveTime.setSingleStep(10)
        self.spinBoxODMRMicrowaveTime.setObjectName("spinBoxODMRMicrowaveTime")
        self.gridLayout_11.addWidget(self.spinBoxODMRMicrowaveTime, 9, 1, 1, 1)
        self.checkBoxODMRMicrowaveOnOff = QtWidgets.QCheckBox(self.groupBoxODMRSequenceConfiguration)
        self.checkBoxODMRMicrowaveOnOff.setObjectName("checkBoxODMRMicrowaveOnOff")
        self.gridLayout_11.addWidget(self.checkBoxODMRMicrowaveOnOff, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 14, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 17, 0, 1, 1)
        self.spinBoxODMRPeriodInterval = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRPeriodInterval.setMaximum(100000)
        self.spinBoxODMRPeriodInterval.setSingleStep(10)
        self.spinBoxODMRPeriodInterval.setObjectName("spinBoxODMRPeriodInterval")
        self.gridLayout_11.addWidget(self.spinBoxODMRPeriodInterval, 17, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 9, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_10.setObjectName("label_10")
        self.gridLayout_11.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 10, 0, 1, 1)
        self.checkBoxODMRWithReference = QtWidgets.QCheckBox(self.groupBoxODMRSequenceConfiguration)
        self.checkBoxODMRWithReference.setObjectName("checkBoxODMRWithReference")
        self.gridLayout_11.addWidget(self.checkBoxODMRWithReference, 2, 0, 1, 1)
        self.spinBoxODMRLaserTime = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRLaserTime.setMaximum(100000)
        self.spinBoxODMRLaserTime.setSingleStep(10)
        self.spinBoxODMRLaserTime.setObjectName("spinBoxODMRLaserTime")
        self.gridLayout_11.addWidget(self.spinBoxODMRLaserTime, 4, 1, 1, 1)
        self.spinBoxODMRLaserMicrowaveInterval = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRLaserMicrowaveInterval.setMaximum(100000)
        self.spinBoxODMRLaserMicrowaveInterval.setSingleStep(10)
        self.spinBoxODMRLaserMicrowaveInterval.setObjectName("spinBoxODMRLaserMicrowaveInterval")
        self.gridLayout_11.addWidget(self.spinBoxODMRLaserMicrowaveInterval, 8, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_21.setObjectName("label_21")
        self.gridLayout_11.addWidget(self.label_21, 15, 0, 1, 1)
        self.spinBoxODMRSignalReferenceInterval = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRSignalReferenceInterval.setMaximum(100000)
        self.spinBoxODMRSignalReferenceInterval.setSingleStep(10)
        self.spinBoxODMRSignalReferenceInterval.setObjectName("spinBoxODMRSignalReferenceInterval")
        self.gridLayout_11.addWidget(self.spinBoxODMRSignalReferenceInterval, 15, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBoxODMRSequenceConfiguration)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 3, 0, 1, 1)
        self.spinBoxODMRSyncFrequency = QtWidgets.QSpinBox(self.groupBoxODMRSequenceConfiguration)
        self.spinBoxODMRSyncFrequency.setPrefix("")
        self.spinBoxODMRSyncFrequency.setMinimum(10)
        self.spinBoxODMRSyncFrequency.setMaximum(1000)
        self.spinBoxODMRSyncFrequency.setSingleStep(10)
        self.spinBoxODMRSyncFrequency.setProperty("value", 50)
        self.spinBoxODMRSyncFrequency.setObjectName("spinBoxODMRSyncFrequency")
        self.gridLayout_11.addWidget(self.spinBoxODMRSyncFrequency, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxODMRSequenceConfiguration)
        self.toolBox.addItem(self.pageODMR, "")
        self.pageSpin = QtWidgets.QWidget()
        self.pageSpin.setGeometry(QtCore.QRect(0, 0, 517, 1025))
        self.pageSpin.setObjectName("pageSpin")
        self.toolBox.addItem(self.pageSpin, "")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tabPhotonCount = QtWidgets.QWidget()
        self.tabPhotonCount.setObjectName("tabPhotonCount")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tabPhotonCount)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.groupBoxPhotonCountCongiuration = QtWidgets.QGroupBox(self.tabPhotonCount)
        self.groupBoxPhotonCountCongiuration.setObjectName("groupBoxPhotonCountCongiuration")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxPhotonCountCongiuration)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelBinWidth = QtWidgets.QLabel(self.groupBoxPhotonCountCongiuration)
        self.labelBinWidth.setObjectName("labelBinWidth")
        self.gridLayout_3.addWidget(self.labelBinWidth, 0, 0, 1, 1)
        self.comboBoxBinwidthUnit = QtWidgets.QComboBox(self.groupBoxPhotonCountCongiuration)
        self.comboBoxBinwidthUnit.setObjectName("comboBoxBinwidthUnit")
        self.comboBoxBinwidthUnit.addItem("")
        self.comboBoxBinwidthUnit.addItem("")
        self.comboBoxBinwidthUnit.addItem("")
        self.comboBoxBinwidthUnit.addItem("")
        self.comboBoxBinwidthUnit.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxBinwidthUnit, 0, 2, 1, 1)
        self.labelCountNumber = QtWidgets.QLabel(self.groupBoxPhotonCountCongiuration)
        self.labelCountNumber.setObjectName("labelCountNumber")
        self.gridLayout_3.addWidget(self.labelCountNumber, 1, 0, 1, 1)
        self.spinBoxBinwidth = QtWidgets.QSpinBox(self.groupBoxPhotonCountCongiuration)
        self.spinBoxBinwidth.setMinimum(1)
        self.spinBoxBinwidth.setMaximum(1000)
        self.spinBoxBinwidth.setObjectName("spinBoxBinwidth")
        self.gridLayout_3.addWidget(self.spinBoxBinwidth, 0, 1, 1, 1)
        self.spinBoxCountNumber = QtWidgets.QSpinBox(self.groupBoxPhotonCountCongiuration)
        self.spinBoxCountNumber.setMinimum(1)
        self.spinBoxCountNumber.setMaximum(5000)
        self.spinBoxCountNumber.setProperty("value", 1000)
        self.spinBoxCountNumber.setObjectName("spinBoxCountNumber")
        self.gridLayout_3.addWidget(self.spinBoxCountNumber, 1, 1, 1, 1)
        self.radioButtonPhotonCountRate = QtWidgets.QRadioButton(self.groupBoxPhotonCountCongiuration)
        self.radioButtonPhotonCountRate.setChecked(True)
        self.radioButtonPhotonCountRate.setObjectName("radioButtonPhotonCountRate")
        self.gridLayout_3.addWidget(self.radioButtonPhotonCountRate, 1, 2, 1, 1)
        self.gridLayout_13.addWidget(self.groupBoxPhotonCountCongiuration, 0, 0, 1, 1)
        self.groupBoxPhotonCountVisualization = QtWidgets.QGroupBox(self.tabPhotonCount)
        self.groupBoxPhotonCountVisualization.setObjectName("groupBoxPhotonCountVisualization")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBoxPhotonCountVisualization)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.widgetPhotonCountVisualization = QtWidgets.QWidget(self.groupBoxPhotonCountVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetPhotonCountVisualization.sizePolicy().hasHeightForWidth())
        self.widgetPhotonCountVisualization.setSizePolicy(sizePolicy)
        self.widgetPhotonCountVisualization.setObjectName("widgetPhotonCountVisualization")
        self.gridLayout_10.addWidget(self.widgetPhotonCountVisualization, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBoxPhotonCountVisualization, 2, 0, 1, 1)
        self.groupBoxPhotonCountOperation = QtWidgets.QGroupBox(self.tabPhotonCount)
        self.groupBoxPhotonCountOperation.setObjectName("groupBoxPhotonCountOperation")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxPhotonCountOperation)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonPhotonCountOnOff = QtWidgets.QPushButton(self.groupBoxPhotonCountOperation)
        self.pushButtonPhotonCountOnOff.setCheckable(True)
        self.pushButtonPhotonCountOnOff.setChecked(False)
        self.pushButtonPhotonCountOnOff.setObjectName("pushButtonPhotonCountOnOff")
        self.horizontalLayout.addWidget(self.pushButtonPhotonCountOnOff)
        self.pushButtonPhotonCountRefresh = QtWidgets.QPushButton(self.groupBoxPhotonCountOperation)
        self.pushButtonPhotonCountRefresh.setObjectName("pushButtonPhotonCountRefresh")
        self.horizontalLayout.addWidget(self.pushButtonPhotonCountRefresh)
        self.pushButtonPhotonCountSaveData = QtWidgets.QPushButton(self.groupBoxPhotonCountOperation)
        self.pushButtonPhotonCountSaveData.setObjectName("pushButtonPhotonCountSaveData")
        self.horizontalLayout.addWidget(self.pushButtonPhotonCountSaveData)
        self.pushButtonTaggerConnect = QtWidgets.QPushButton(self.groupBoxPhotonCountOperation)
        self.pushButtonTaggerConnect.setObjectName("pushButtonTaggerConnect")
        self.horizontalLayout.addWidget(self.pushButtonTaggerConnect)
        self.pushButtonTaggerClose = QtWidgets.QPushButton(self.groupBoxPhotonCountOperation)
        self.pushButtonTaggerClose.setObjectName("pushButtonTaggerClose")
        self.horizontalLayout.addWidget(self.pushButtonTaggerClose)
        self.gridLayout_13.addWidget(self.groupBoxPhotonCountOperation, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabPhotonCount, "")
        self.tabASGSequence = QtWidgets.QWidget()
        self.tabASGSequence.setObjectName("tabASGSequence")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabASGSequence)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBoxSequenceVisualization = QtWidgets.QGroupBox(self.tabASGSequence)
        self.groupBoxSequenceVisualization.setObjectName("groupBoxSequenceVisualization")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBoxSequenceVisualization)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.widgetSequenceVisualization = QtWidgets.QWidget(self.groupBoxSequenceVisualization)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetSequenceVisualization.sizePolicy().hasHeightForWidth())
        self.widgetSequenceVisualization.setSizePolicy(sizePolicy)
        self.widgetSequenceVisualization.setObjectName("widgetSequenceVisualization")
        self.gridLayout_17.addWidget(self.widgetSequenceVisualization, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxSequenceVisualization, 1, 0, 1, 1)
        self.groupBoxSequenceConfiguration = QtWidgets.QGroupBox(self.tabASGSequence)
        self.groupBoxSequenceConfiguration.setObjectName("groupBoxSequenceConfiguration")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxSequenceConfiguration)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetSequence = QtWidgets.QTableWidget(self.groupBoxSequenceConfiguration)
        self.tableWidgetSequence.setObjectName("tableWidgetSequence")
        self.tableWidgetSequence.setColumnCount(14)
        self.tableWidgetSequence.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSequence.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.tableWidgetSequence.setItem(0, 0, item)
        self.tableWidgetSequence.horizontalHeader().setDefaultSectionSize(60)
        self.tableWidgetSequence.verticalHeader().setDefaultSectionSize(35)
        self.gridLayout.addWidget(self.tableWidgetSequence, 0, 0, 1, 2)
        self.groupBoxASGDevice = QtWidgets.QGroupBox(self.groupBoxSequenceConfiguration)
        self.groupBoxASGDevice.setObjectName("groupBoxASGDevice")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBoxASGDevice)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonASGOpen = QtWidgets.QPushButton(self.groupBoxASGDevice)
        self.pushButtonASGOpen.setObjectName("pushButtonASGOpen")
        self.horizontalLayout_3.addWidget(self.pushButtonASGOpen)
        self.pushButtonASGClose = QtWidgets.QPushButton(self.groupBoxASGDevice)
        self.pushButtonASGClose.setObjectName("pushButtonASGClose")
        self.horizontalLayout_3.addWidget(self.pushButtonASGClose)
        self.pushButtonASGStart = QtWidgets.QPushButton(self.groupBoxASGDevice)
        self.pushButtonASGStart.setObjectName("pushButtonASGStart")
        self.horizontalLayout_3.addWidget(self.pushButtonASGStart)
        self.pushButtonASGStop = QtWidgets.QPushButton(self.groupBoxASGDevice)
        self.pushButtonASGStop.setObjectName("pushButtonASGStop")
        self.horizontalLayout_3.addWidget(self.pushButtonASGStop)
        self.gridLayout.addWidget(self.groupBoxASGDevice, 1, 0, 1, 1)
        self.groupBoxASGPulse = QtWidgets.QGroupBox(self.groupBoxSequenceConfiguration)
        self.groupBoxASGPulse.setObjectName("groupBoxASGPulse")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBoxASGPulse)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonASGLoad = QtWidgets.QPushButton(self.groupBoxASGPulse)
        self.pushButtonASGLoad.setObjectName("pushButtonASGLoad")
        self.horizontalLayout_2.addWidget(self.pushButtonASGLoad)
        self.pushButtonASGClear = QtWidgets.QPushButton(self.groupBoxASGPulse)
        self.pushButtonASGClear.setObjectName("pushButtonASGClear")
        self.horizontalLayout_2.addWidget(self.pushButtonASGClear)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBoxASGPulse)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButtonASGAdd = QtWidgets.QPushButton(self.groupBoxASGPulse)
        self.pushButtonASGAdd.setObjectName("pushButtonASGAdd")
        self.horizontalLayout_2.addWidget(self.pushButtonASGAdd)
        self.gridLayout.addWidget(self.groupBoxASGPulse, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBoxSequenceConfiguration, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabASGSequence, "")
        self.tabODMRFrequency = QtWidgets.QWidget()
        self.tabODMRFrequency.setObjectName("tabODMRFrequency")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabODMRFrequency)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBoxODMRFrequencyChartOperation = QtWidgets.QGroupBox(self.tabODMRFrequency)
        self.groupBoxODMRFrequencyChartOperation.setObjectName("groupBoxODMRFrequencyChartOperation")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBoxODMRFrequencyChartOperation)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.pushButtonODMRFrequencyInterrupt = QtWidgets.QPushButton(self.groupBoxODMRFrequencyChartOperation)
        self.pushButtonODMRFrequencyInterrupt.setObjectName("pushButtonODMRFrequencyInterrupt")
        self.gridLayout_15.addWidget(self.pushButtonODMRFrequencyInterrupt, 0, 0, 1, 1)
        self.pushButtonODMRFrequencySave = QtWidgets.QPushButton(self.groupBoxODMRFrequencyChartOperation)
        self.pushButtonODMRFrequencySave.setObjectName("pushButtonODMRFrequencySave")
        self.gridLayout_15.addWidget(self.pushButtonODMRFrequencySave, 0, 1, 1, 1)
        self.radioButtonODMRFrequencyShowCount = QtWidgets.QRadioButton(self.groupBoxODMRFrequencyChartOperation)
        self.radioButtonODMRFrequencyShowCount.setChecked(True)
        self.radioButtonODMRFrequencyShowCount.setObjectName("radioButtonODMRFrequencyShowCount")
        self.gridLayout_15.addWidget(self.radioButtonODMRFrequencyShowCount, 0, 2, 1, 1)
        self.pushButtonODMRFrequencyFit = QtWidgets.QPushButton(self.groupBoxODMRFrequencyChartOperation)
        self.pushButtonODMRFrequencyFit.setObjectName("pushButtonODMRFrequencyFit")
        self.gridLayout_15.addWidget(self.pushButtonODMRFrequencyFit, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBoxODMRFrequencyChartOperation)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_15.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.radioButtonODMRFrequencyShowContrast = QtWidgets.QRadioButton(self.groupBoxODMRFrequencyChartOperation)
        self.radioButtonODMRFrequencyShowContrast.setObjectName("radioButtonODMRFrequencyShowContrast")
        self.gridLayout_15.addWidget(self.radioButtonODMRFrequencyShowContrast, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxODMRFrequencyChartOperation, 0, 0, 1, 1)
        self.groupBoxODMRFrequencyChart = QtWidgets.QGroupBox(self.tabODMRFrequency)
        self.groupBoxODMRFrequencyChart.setObjectName("groupBoxODMRFrequencyChart")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBoxODMRFrequencyChart)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widgetODMRFrequencyVisualization = QtWidgets.QWidget(self.groupBoxODMRFrequencyChart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetODMRFrequencyVisualization.sizePolicy().hasHeightForWidth())
        self.widgetODMRFrequencyVisualization.setSizePolicy(sizePolicy)
        self.widgetODMRFrequencyVisualization.setObjectName("widgetODMRFrequencyVisualization")
        self.gridLayout_8.addWidget(self.widgetODMRFrequencyVisualization, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBoxODMRFrequencyChart, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabODMRFrequency, "")
        self.tabODMRTime = QtWidgets.QWidget()
        self.tabODMRTime.setObjectName("tabODMRTime")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabODMRTime)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBoxODMRTimeChartOperation = QtWidgets.QGroupBox(self.tabODMRTime)
        self.groupBoxODMRTimeChartOperation.setObjectName("groupBoxODMRTimeChartOperation")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBoxODMRTimeChartOperation)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.pushButtonODMRTimeInterreupt = QtWidgets.QPushButton(self.groupBoxODMRTimeChartOperation)
        self.pushButtonODMRTimeInterreupt.setObjectName("pushButtonODMRTimeInterreupt")
        self.gridLayout_16.addWidget(self.pushButtonODMRTimeInterreupt, 0, 0, 1, 1)
        self.pushButtonODMRTimeSave = QtWidgets.QPushButton(self.groupBoxODMRTimeChartOperation)
        self.pushButtonODMRTimeSave.setObjectName("pushButtonODMRTimeSave")
        self.gridLayout_16.addWidget(self.pushButtonODMRTimeSave, 0, 1, 1, 1)
        self.pushButtonODMRTimeFit = QtWidgets.QPushButton(self.groupBoxODMRTimeChartOperation)
        self.pushButtonODMRTimeFit.setObjectName("pushButtonODMRTimeFit")
        self.gridLayout_16.addWidget(self.pushButtonODMRTimeFit, 1, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBoxODMRTimeChartOperation)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_16.addWidget(self.pushButton_12, 1, 1, 1, 1)
        self.radioButtonODMRTimeShowCount = QtWidgets.QRadioButton(self.groupBoxODMRTimeChartOperation)
        self.radioButtonODMRTimeShowCount.setChecked(True)
        self.radioButtonODMRTimeShowCount.setObjectName("radioButtonODMRTimeShowCount")
        self.gridLayout_16.addWidget(self.radioButtonODMRTimeShowCount, 0, 2, 1, 1)
        self.radioButtonODMRTimeShowContrast = QtWidgets.QRadioButton(self.groupBoxODMRTimeChartOperation)
        self.radioButtonODMRTimeShowContrast.setObjectName("radioButtonODMRTimeShowContrast")
        self.gridLayout_16.addWidget(self.radioButtonODMRTimeShowContrast, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBoxODMRTimeChartOperation)
        self.groupBoxODMRTimeChart = QtWidgets.QGroupBox(self.tabODMRTime)
        self.groupBoxODMRTimeChart.setObjectName("groupBoxODMRTimeChart")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBoxODMRTimeChart)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.widgetODMRTimeVisualization = QtWidgets.QWidget(self.groupBoxODMRTimeChart)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetODMRTimeVisualization.sizePolicy().hasHeightForWidth())
        self.widgetODMRTimeVisualization.setSizePolicy(sizePolicy)
        self.widgetODMRTimeVisualization.setObjectName("widgetODMRTimeVisualization")
        self.gridLayout_14.addWidget(self.widgetODMRTimeVisualization, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBoxODMRTimeChart)
        self.tabWidget.addTab(self.tabODMRTime, "")
        self.gridLayout_9.addWidget(self.splitter, 0, 0, 1, 1)
        OdmactorMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OdmactorMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1512, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout_A = QtWidgets.QMenu(self.menubar)
        self.menuAbout_A.setObjectName("menuAbout_A")
        OdmactorMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OdmactorMainWindow)
        self.statusbar.setObjectName("statusbar")
        OdmactorMainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(OdmactorMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(OdmactorMainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionQtInfo = QtWidgets.QAction(OdmactorMainWindow)
        self.actionQtInfo.setObjectName("actionQtInfo")
        self.menuAbout_A.addAction(self.actionAbout)
        self.menuAbout_A.addAction(self.actionHelp)
        self.menuAbout_A.addAction(self.actionQtInfo)
        self.menubar.addAction(self.menuAbout_A.menuAction())

        self.retranslateUi(OdmactorMainWindow)
        self.toolBox.setCurrentIndex(1)
        self.comboBoxMicrowaveFrequencyUnit.setCurrentIndex(0)
        self.comboBoxMicrowavePiPulseFrequencyUnit.setCurrentIndex(1)
        self.comboBoxMicrowavePiPulsePowerUnit.setCurrentIndex(0)
        self.comboBoxASGTagger.setCurrentIndex(4)
        self.comboBoxASGAPD.setCurrentIndex(2)
        self.comboBoxASGMicrowave.setCurrentIndex(1)
        self.comboBoxASGLockinSync.setCurrentIndex(7)
        self.comboBoxASGMicrowaveSync.setCurrentIndex(3)
        self.comboBoxTaggerTrigger.setCurrentIndex(1)
        self.comboBoxODMRFrequencyUnit.setCurrentIndex(1)
        self.comboBoxODMRTimeUnit.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)
        self.comboBoxBinwidthUnit.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(OdmactorMainWindow)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxMicrowaveFrequency, self.comboBoxMicrowaveFrequencyUnit)
        OdmactorMainWindow.setTabOrder(self.comboBoxMicrowaveFrequencyUnit, self.doubleSpinBoxMicrowavePower)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxMicrowavePower, self.comboBoxMicrowavePowerUnit)
        OdmactorMainWindow.setTabOrder(self.comboBoxMicrowavePowerUnit, self.pushButtonMicrowaveOnOff)
        OdmactorMainWindow.setTabOrder(self.pushButtonMicrowaveOnOff, self.pushButtonMicrowaveConnect)
        OdmactorMainWindow.setTabOrder(self.pushButtonMicrowaveConnect, self.pushButtonMicrowaveClose)
        OdmactorMainWindow.setTabOrder(self.pushButtonMicrowaveClose, self.groupBoxMicrowaveTimer)
        OdmactorMainWindow.setTabOrder(self.groupBoxMicrowaveTimer, self.doubleSpinBoxMicrowaveTimerTime)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxMicrowaveTimerTime, self.comboBoxMicrowaveTimerTimeUnit)
        OdmactorMainWindow.setTabOrder(self.comboBoxMicrowaveTimerTimeUnit, self.doubleSpinBoxMicrowavePiPulseFrequency)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxMicrowavePiPulseFrequency, self.comboBoxMicrowavePiPulseFrequencyUnit)
        OdmactorMainWindow.setTabOrder(self.comboBoxMicrowavePiPulseFrequencyUnit, self.doubleSpinBoxMicrowavePiPulseDuration)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxMicrowavePiPulseDuration, self.comboBoxMicrowavePiPulseDurationUnit)
        OdmactorMainWindow.setTabOrder(self.comboBoxMicrowavePiPulseDurationUnit, self.doubleSpinBoxMicrowavePiPulsePower)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxMicrowavePiPulsePower, self.comboBoxMicrowavePiPulsePowerUnit)
        OdmactorMainWindow.setTabOrder(self.comboBoxMicrowavePiPulsePowerUnit, self.radioButtonLaserCW)
        OdmactorMainWindow.setTabOrder(self.radioButtonLaserCW, self.radioButtonLaserPulse)
        OdmactorMainWindow.setTabOrder(self.radioButtonLaserPulse, self.pushButtonLaserOnOff)
        OdmactorMainWindow.setTabOrder(self.pushButtonLaserOnOff, self.doubleSpinBoxLaserPower)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxLaserPower, self.pushButtonLaserConnect)
        OdmactorMainWindow.setTabOrder(self.pushButtonLaserConnect, self.pushButtonLaserClose)
        OdmactorMainWindow.setTabOrder(self.pushButtonLaserClose, self.comboBoxASGLaser)
        OdmactorMainWindow.setTabOrder(self.comboBoxASGLaser, self.comboBoxASGMicrowave)
        OdmactorMainWindow.setTabOrder(self.comboBoxASGMicrowave, self.comboBoxASGMicrowaveSync)
        OdmactorMainWindow.setTabOrder(self.comboBoxASGMicrowaveSync, self.comboBoxASGAPD)
        OdmactorMainWindow.setTabOrder(self.comboBoxASGAPD, self.comboBoxASGTagger)
        OdmactorMainWindow.setTabOrder(self.comboBoxASGTagger, self.comboBoxASGLockinSync)
        OdmactorMainWindow.setTabOrder(self.comboBoxASGLockinSync, self.checkBoxASGLaserTTL)
        OdmactorMainWindow.setTabOrder(self.checkBoxASGLaserTTL, self.checkBoxASGMicrowaveTTL)
        OdmactorMainWindow.setTabOrder(self.checkBoxASGMicrowaveTTL, self.checkBoxASGMicrowaveSync)
        OdmactorMainWindow.setTabOrder(self.checkBoxASGMicrowaveSync, self.checkBoxASGAPDTTL)
        OdmactorMainWindow.setTabOrder(self.checkBoxASGAPDTTL, self.checkBoxASGTaggerTTL)
        OdmactorMainWindow.setTabOrder(self.checkBoxASGTaggerTTL, self.checkBoxASGLockinSyncTTL)
        OdmactorMainWindow.setTabOrder(self.checkBoxASGLockinSyncTTL, self.comboBoxTaggerAPD)
        OdmactorMainWindow.setTabOrder(self.comboBoxTaggerAPD, self.comboBoxTaggerTrigger)
        OdmactorMainWindow.setTabOrder(self.comboBoxTaggerTrigger, self.radioButtonUseTagger)
        OdmactorMainWindow.setTabOrder(self.radioButtonUseTagger, self.radioButtonUseLockin)
        OdmactorMainWindow.setTabOrder(self.radioButtonUseLockin, self.pushButtonODMRLoadSequences)
        OdmactorMainWindow.setTabOrder(self.pushButtonODMRLoadSequences, self.pushButtonODMRStartDetecting)
        OdmactorMainWindow.setTabOrder(self.pushButtonODMRStartDetecting, self.pushButtonODMRSaveData)
        OdmactorMainWindow.setTabOrder(self.pushButtonODMRSaveData, self.groupBoxODMRFrequency)
        OdmactorMainWindow.setTabOrder(self.groupBoxODMRFrequency, self.radioButtonODMRCW)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRCW, self.radioButtonODMRPulse)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRPulse, self.checkBoxODMRFrequencyScanning)
        OdmactorMainWindow.setTabOrder(self.checkBoxODMRFrequencyScanning, self.comboBoxODMRFrequencyUnit)
        OdmactorMainWindow.setTabOrder(self.comboBoxODMRFrequencyUnit, self.doubleSpinBoxODMRFrequencyStart)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxODMRFrequencyStart, self.doubleSpinBoxODMRFrequencyEnd)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxODMRFrequencyEnd, self.doubleSpinBoxODMRFrequencyStep)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxODMRFrequencyStep, self.groupBoxODMRTime)
        OdmactorMainWindow.setTabOrder(self.groupBoxODMRTime, self.radioButtonODMRRabi)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRRabi, self.radioButtonODMRRamsey)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRRamsey, self.radioButtonPulseODMRRelaxation)
        OdmactorMainWindow.setTabOrder(self.radioButtonPulseODMRRelaxation, self.checkBoxODMRTimeScanning)
        OdmactorMainWindow.setTabOrder(self.checkBoxODMRTimeScanning, self.comboBoxODMRTimeUnit)
        OdmactorMainWindow.setTabOrder(self.comboBoxODMRTimeUnit, self.doubleSpinBoxODMRTimeStart)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxODMRTimeStart, self.doubleSpinBoxODMRTimeEnd)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxODMRTimeEnd, self.doubleSpinBoxODMRTimeStep)
        OdmactorMainWindow.setTabOrder(self.doubleSpinBoxODMRTimeStep, self.spinBoxODMRTimeLength)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRTimeLength, self.radioButtonODMRTimeUseStep)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRTimeUseStep, self.radioButtonODMRTimeUseLength)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRTimeUseLength, self.radioButtonODMRTimeUseLengthAndLogarithm)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRTimeUseLengthAndLogarithm, self.spinBoxODMRPeriodNumber)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRPeriodNumber, self.checkBoxODMRWithReference)
        OdmactorMainWindow.setTabOrder(self.checkBoxODMRWithReference, self.checkBoxODMRMicrowaveOnOff)
        OdmactorMainWindow.setTabOrder(self.checkBoxODMRMicrowaveOnOff, self.spinBoxODMRSyncFrequency)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRSyncFrequency, self.spinBoxODMRLaserTime)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRLaserTime, self.spinBoxODMRLaserMicrowaveInterval)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRLaserMicrowaveInterval, self.spinBoxODMRMicrowaveTime)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRMicrowaveTime, self.spinBoxODMRMicrowaveReadoutInterval)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRMicrowaveReadoutInterval, self.spinBoxODMRPreReadoutInterval)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRPreReadoutInterval, self.spinBoxODMRSignalReadoutTime)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRSignalReadoutTime, self.spinBoxODMRSignalReferenceInterval)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRSignalReferenceInterval, self.spinBoxODMRPeriodInterval)
        OdmactorMainWindow.setTabOrder(self.spinBoxODMRPeriodInterval, self.tabWidget)
        OdmactorMainWindow.setTabOrder(self.tabWidget, self.spinBoxBinwidth)
        OdmactorMainWindow.setTabOrder(self.spinBoxBinwidth, self.comboBoxBinwidthUnit)
        OdmactorMainWindow.setTabOrder(self.comboBoxBinwidthUnit, self.spinBoxCountNumber)
        OdmactorMainWindow.setTabOrder(self.spinBoxCountNumber, self.radioButtonPhotonCountRate)
        OdmactorMainWindow.setTabOrder(self.radioButtonPhotonCountRate, self.pushButtonPhotonCountOnOff)
        OdmactorMainWindow.setTabOrder(self.pushButtonPhotonCountOnOff, self.pushButtonPhotonCountRefresh)
        OdmactorMainWindow.setTabOrder(self.pushButtonPhotonCountRefresh, self.pushButtonPhotonCountSaveData)
        OdmactorMainWindow.setTabOrder(self.pushButtonPhotonCountSaveData, self.pushButtonTaggerConnect)
        OdmactorMainWindow.setTabOrder(self.pushButtonTaggerConnect, self.pushButtonTaggerClose)
        OdmactorMainWindow.setTabOrder(self.pushButtonTaggerClose, self.tableWidgetSequence)
        OdmactorMainWindow.setTabOrder(self.tableWidgetSequence, self.pushButtonASGOpen)
        OdmactorMainWindow.setTabOrder(self.pushButtonASGOpen, self.pushButtonASGClose)
        OdmactorMainWindow.setTabOrder(self.pushButtonASGClose, self.pushButtonASGStart)
        OdmactorMainWindow.setTabOrder(self.pushButtonASGStart, self.pushButtonASGStop)
        OdmactorMainWindow.setTabOrder(self.pushButtonASGStop, self.pushButtonASGLoad)
        OdmactorMainWindow.setTabOrder(self.pushButtonASGLoad, self.pushButtonASGClear)
        OdmactorMainWindow.setTabOrder(self.pushButtonASGClear, self.pushButton_3)
        OdmactorMainWindow.setTabOrder(self.pushButton_3, self.pushButtonASGAdd)
        OdmactorMainWindow.setTabOrder(self.pushButtonASGAdd, self.pushButtonODMRFrequencyInterrupt)
        OdmactorMainWindow.setTabOrder(self.pushButtonODMRFrequencyInterrupt, self.pushButtonODMRFrequencySave)
        OdmactorMainWindow.setTabOrder(self.pushButtonODMRFrequencySave, self.radioButtonODMRFrequencyShowCount)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRFrequencyShowCount, self.pushButtonODMRFrequencyFit)
        OdmactorMainWindow.setTabOrder(self.pushButtonODMRFrequencyFit, self.pushButton_8)
        OdmactorMainWindow.setTabOrder(self.pushButton_8, self.radioButtonODMRFrequencyShowContrast)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRFrequencyShowContrast, self.pushButtonODMRTimeInterreupt)
        OdmactorMainWindow.setTabOrder(self.pushButtonODMRTimeInterreupt, self.pushButtonODMRTimeSave)
        OdmactorMainWindow.setTabOrder(self.pushButtonODMRTimeSave, self.pushButtonODMRTimeFit)
        OdmactorMainWindow.setTabOrder(self.pushButtonODMRTimeFit, self.pushButton_12)
        OdmactorMainWindow.setTabOrder(self.pushButton_12, self.radioButtonODMRTimeShowCount)
        OdmactorMainWindow.setTabOrder(self.radioButtonODMRTimeShowCount, self.radioButtonODMRTimeShowContrast)

    def retranslateUi(self, OdmactorMainWindow):
        _translate = QtCore.QCoreApplication.translate
        OdmactorMainWindow.setWindowTitle(_translate("OdmactorMainWindow", "ODMACTOR"))
        self.groupBoxMicrowaveControl.setTitle(_translate("OdmactorMainWindow", "Microwave Control"))
        self.labelMicrowaveFrequency.setText(_translate("OdmactorMainWindow", "Frequency"))
        self.comboBoxMicrowaveFrequencyUnit.setItemText(0, _translate("OdmactorMainWindow", "GHz"))
        self.comboBoxMicrowaveFrequencyUnit.setItemText(1, _translate("OdmactorMainWindow", "MHz"))
        self.comboBoxMicrowaveFrequencyUnit.setItemText(2, _translate("OdmactorMainWindow", "KHz"))
        self.comboBoxMicrowaveFrequencyUnit.setItemText(3, _translate("OdmactorMainWindow", "Hz"))
        self.labelMicrowavePower.setText(_translate("OdmactorMainWindow", "Power"))
        self.comboBoxMicrowavePowerUnit.setItemText(0, _translate("OdmactorMainWindow", "dBm"))
        self.comboBoxMicrowavePowerUnit.setItemText(1, _translate("OdmactorMainWindow", "mW"))
        self.pushButtonMicrowaveOnOff.setText(_translate("OdmactorMainWindow", "On/Off"))
        self.pushButtonMicrowaveConnect.setText(_translate("OdmactorMainWindow", "Connect"))
        self.pushButtonMicrowaveClose.setText(_translate("OdmactorMainWindow", "Close"))
        self.groupBoxMicrowaveTimer.setTitle(_translate("OdmactorMainWindow", "Timer"))
        self.labelMicrowaveTimer.setText(_translate("OdmactorMainWindow", "Running time"))
        self.comboBoxMicrowaveTimerTimeUnit.setItemText(0, _translate("OdmactorMainWindow", "s"))
        self.comboBoxMicrowaveTimerTimeUnit.setItemText(1, _translate("OdmactorMainWindow", "ms"))
        self.comboBoxMicrowaveTimerTimeUnit.setItemText(2, _translate("OdmactorMainWindow", "us"))
        self.groupBoxMicrowavePiPulse.setTitle(_translate("OdmactorMainWindow", "Pi Pulse"))
        self.labelMicrowavePiPulsePiPulseFrequency.setText(_translate("OdmactorMainWindow", "Frequency"))
        self.comboBoxMicrowavePiPulseFrequencyUnit.setItemText(0, _translate("OdmactorMainWindow", "GHz"))
        self.comboBoxMicrowavePiPulseFrequencyUnit.setItemText(1, _translate("OdmactorMainWindow", "MHz"))
        self.comboBoxMicrowavePiPulseFrequencyUnit.setItemText(2, _translate("OdmactorMainWindow", "KHz"))
        self.comboBoxMicrowavePiPulseFrequencyUnit.setItemText(3, _translate("OdmactorMainWindow", "Hz"))
        self.labelMicrowavePiPulseDuration.setText(_translate("OdmactorMainWindow", "Duration"))
        self.comboBoxMicrowavePiPulseDurationUnit.setItemText(0, _translate("OdmactorMainWindow", "ms"))
        self.comboBoxMicrowavePiPulseDurationUnit.setItemText(1, _translate("OdmactorMainWindow", "us"))
        self.comboBoxMicrowavePiPulseDurationUnit.setItemText(2, _translate("OdmactorMainWindow", "ns"))
        self.labelMicrowavePiPulsePower.setText(_translate("OdmactorMainWindow", "Power"))
        self.comboBoxMicrowavePiPulsePowerUnit.setItemText(0, _translate("OdmactorMainWindow", "dBm"))
        self.comboBoxMicrowavePiPulsePowerUnit.setItemText(1, _translate("OdmactorMainWindow", "mW"))
        self.groupBoxLaserControl.setTitle(_translate("OdmactorMainWindow", "Laser Control"))
        self.radioButtonLaserCW.setText(_translate("OdmactorMainWindow", "Continous"))
        self.radioButtonLaserPulse.setText(_translate("OdmactorMainWindow", "Pulse"))
        self.pushButtonLaserOnOff.setText(_translate("OdmactorMainWindow", "On/Off"))
        self.labelLaserPower.setText(_translate("OdmactorMainWindow", "Power"))
        self.doubleSpinBoxLaserPower.setSuffix(_translate("OdmactorMainWindow", "%"))
        self.pushButtonLaserConnect.setText(_translate("OdmactorMainWindow", "Connect"))
        self.pushButtonLaserClose.setText(_translate("OdmactorMainWindow", "Close"))
        self.label_2.setText(_translate("OdmactorMainWindow", "This function is not implemented ...(AOM)"))
        self.groupBoxASGChannels.setTitle(_translate("OdmactorMainWindow", "ASG Control Channels"))
        self.labelHistType.setText(_translate("OdmactorMainWindow", "Laser"))
        self.labelSplit.setText(_translate("OdmactorMainWindow", "Microwave"))
        self.comboBoxASGLaser.setItemText(0, _translate("OdmactorMainWindow", "1"))
        self.comboBoxASGLaser.setItemText(1, _translate("OdmactorMainWindow", "2"))
        self.comboBoxASGLaser.setItemText(2, _translate("OdmactorMainWindow", "3"))
        self.comboBoxASGLaser.setItemText(3, _translate("OdmactorMainWindow", "4"))
        self.comboBoxASGLaser.setItemText(4, _translate("OdmactorMainWindow", "5"))
        self.comboBoxASGLaser.setItemText(5, _translate("OdmactorMainWindow", "6"))
        self.comboBoxASGLaser.setItemText(6, _translate("OdmactorMainWindow", "7"))
        self.comboBoxASGLaser.setItemText(7, _translate("OdmactorMainWindow", "8"))
        self.label_12.setText(_translate("OdmactorMainWindow", "Tagger Trigger"))
        self.comboBoxASGTagger.setItemText(0, _translate("OdmactorMainWindow", "1"))
        self.comboBoxASGTagger.setItemText(1, _translate("OdmactorMainWindow", "2"))
        self.comboBoxASGTagger.setItemText(2, _translate("OdmactorMainWindow", "3"))
        self.comboBoxASGTagger.setItemText(3, _translate("OdmactorMainWindow", "4"))
        self.comboBoxASGTagger.setItemText(4, _translate("OdmactorMainWindow", "5"))
        self.comboBoxASGTagger.setItemText(5, _translate("OdmactorMainWindow", "6"))
        self.comboBoxASGTagger.setItemText(6, _translate("OdmactorMainWindow", "7"))
        self.comboBoxASGTagger.setItemText(7, _translate("OdmactorMainWindow", "8"))
        self.comboBoxASGAPD.setItemText(0, _translate("OdmactorMainWindow", "1"))
        self.comboBoxASGAPD.setItemText(1, _translate("OdmactorMainWindow", "2"))
        self.comboBoxASGAPD.setItemText(2, _translate("OdmactorMainWindow", "3"))
        self.comboBoxASGAPD.setItemText(3, _translate("OdmactorMainWindow", "4"))
        self.comboBoxASGAPD.setItemText(4, _translate("OdmactorMainWindow", "5"))
        self.comboBoxASGAPD.setItemText(5, _translate("OdmactorMainWindow", "6"))
        self.comboBoxASGAPD.setItemText(6, _translate("OdmactorMainWindow", "7"))
        self.comboBoxASGAPD.setItemText(7, _translate("OdmactorMainWindow", "8"))
        self.comboBoxASGMicrowave.setCurrentText(_translate("OdmactorMainWindow", "2"))
        self.comboBoxASGMicrowave.setItemText(0, _translate("OdmactorMainWindow", "1"))
        self.comboBoxASGMicrowave.setItemText(1, _translate("OdmactorMainWindow", "2"))
        self.comboBoxASGMicrowave.setItemText(2, _translate("OdmactorMainWindow", "3"))
        self.comboBoxASGMicrowave.setItemText(3, _translate("OdmactorMainWindow", "4"))
        self.comboBoxASGMicrowave.setItemText(4, _translate("OdmactorMainWindow", "5"))
        self.comboBoxASGMicrowave.setItemText(5, _translate("OdmactorMainWindow", "6"))
        self.comboBoxASGMicrowave.setItemText(6, _translate("OdmactorMainWindow", "7"))
        self.comboBoxASGMicrowave.setItemText(7, _translate("OdmactorMainWindow", "8"))
        self.checkBoxASGLaserTTL.setText(_translate("OdmactorMainWindow", "High-level TTL "))
        self.label_11.setText(_translate("OdmactorMainWindow", "Photon Detector"))
        self.checkBoxASGTaggerTTL.setText(_translate("OdmactorMainWindow", "High-level TTL "))
        self.checkBoxASGMicrowaveTTL.setText(_translate("OdmactorMainWindow", "High-level TTL "))
        self.checkBoxASGAPDTTL.setText(_translate("OdmactorMainWindow", "High-level TTL "))
        self.label.setText(_translate("OdmactorMainWindow", "Microwave Sync"))
        self.checkBoxASGMicrowaveSync.setText(_translate("OdmactorMainWindow", "High-level TTL "))
        self.label_4.setText(_translate("OdmactorMainWindow", "Lockin Sync"))
        self.checkBoxASGLockinSyncTTL.setText(_translate("OdmactorMainWindow", "High-level TTL "))
        self.comboBoxASGLockinSync.setItemText(0, _translate("OdmactorMainWindow", "1"))
        self.comboBoxASGLockinSync.setItemText(1, _translate("OdmactorMainWindow", "2"))
        self.comboBoxASGLockinSync.setItemText(2, _translate("OdmactorMainWindow", "3"))
        self.comboBoxASGLockinSync.setItemText(3, _translate("OdmactorMainWindow", "4"))
        self.comboBoxASGLockinSync.setItemText(4, _translate("OdmactorMainWindow", "5"))
        self.comboBoxASGLockinSync.setItemText(5, _translate("OdmactorMainWindow", "6"))
        self.comboBoxASGLockinSync.setItemText(6, _translate("OdmactorMainWindow", "7"))
        self.comboBoxASGLockinSync.setItemText(7, _translate("OdmactorMainWindow", "8"))
        self.comboBoxASGMicrowaveSync.setCurrentText(_translate("OdmactorMainWindow", "4"))
        self.comboBoxASGMicrowaveSync.setItemText(0, _translate("OdmactorMainWindow", "1"))
        self.comboBoxASGMicrowaveSync.setItemText(1, _translate("OdmactorMainWindow", "2"))
        self.comboBoxASGMicrowaveSync.setItemText(2, _translate("OdmactorMainWindow", "3"))
        self.comboBoxASGMicrowaveSync.setItemText(3, _translate("OdmactorMainWindow", "4"))
        self.comboBoxASGMicrowaveSync.setItemText(4, _translate("OdmactorMainWindow", "5"))
        self.comboBoxASGMicrowaveSync.setItemText(5, _translate("OdmactorMainWindow", "6"))
        self.comboBoxASGMicrowaveSync.setItemText(6, _translate("OdmactorMainWindow", "7"))
        self.comboBoxASGMicrowaveSync.setItemText(7, _translate("OdmactorMainWindow", "8"))
        self.groupBoxTaggerChannels.setTitle(_translate("OdmactorMainWindow", "Tagger/Lockin Configuration"))
        self.radioButtonUseTagger.setText(_translate("OdmactorMainWindow", "Use Tagger"))
        self.comboBoxTaggerAPD.setItemText(0, _translate("OdmactorMainWindow", "1"))
        self.comboBoxTaggerAPD.setItemText(1, _translate("OdmactorMainWindow", "2"))
        self.comboBoxTaggerAPD.setItemText(2, _translate("OdmactorMainWindow", "3"))
        self.comboBoxTaggerAPD.setItemText(3, _translate("OdmactorMainWindow", "4"))
        self.comboBoxTaggerAPD.setItemText(4, _translate("OdmactorMainWindow", "5"))
        self.comboBoxTaggerAPD.setItemText(5, _translate("OdmactorMainWindow", "6"))
        self.comboBoxTaggerAPD.setItemText(6, _translate("OdmactorMainWindow", "7"))
        self.comboBoxTaggerAPD.setItemText(7, _translate("OdmactorMainWindow", "8"))
        self.label_15.setText(_translate("OdmactorMainWindow", "Trigger to Tagger"))
        self.comboBoxTaggerTrigger.setCurrentText(_translate("OdmactorMainWindow", "2"))
        self.comboBoxTaggerTrigger.setItemText(0, _translate("OdmactorMainWindow", "1"))
        self.comboBoxTaggerTrigger.setItemText(1, _translate("OdmactorMainWindow", "2"))
        self.comboBoxTaggerTrigger.setItemText(2, _translate("OdmactorMainWindow", "3"))
        self.comboBoxTaggerTrigger.setItemText(3, _translate("OdmactorMainWindow", "4"))
        self.comboBoxTaggerTrigger.setItemText(4, _translate("OdmactorMainWindow", "5"))
        self.comboBoxTaggerTrigger.setItemText(5, _translate("OdmactorMainWindow", "6"))
        self.comboBoxTaggerTrigger.setItemText(6, _translate("OdmactorMainWindow", "7"))
        self.comboBoxTaggerTrigger.setItemText(7, _translate("OdmactorMainWindow", "8"))
        self.radioButtonUseLockin.setText(_translate("OdmactorMainWindow", "Use Lockin"))
        self.label_14.setText(_translate("OdmactorMainWindow", "APD to Tagger"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageGeneric), _translate("OdmactorMainWindow", "Generic Configuration"))
        self.groupBoxODMROperation.setTitle(_translate("OdmactorMainWindow", "Operation"))
        self.pushButtonODMRLoadSequences.setText(_translate("OdmactorMainWindow", "Load Sequences"))
        self.pushButtonODMRStartDetecting.setText(_translate("OdmactorMainWindow", "Start Detecting"))
        self.pushButtonODMRSaveData.setText(_translate("OdmactorMainWindow", "Save Data"))
        self.groupBoxODMRFrequency.setTitle(_translate("OdmactorMainWindow", "Frequency-domain Detecting"))
        self.groupBox_10.setTitle(_translate("OdmactorMainWindow", "Detecting Mode"))
        self.radioButtonODMRCW.setText(_translate("OdmactorMainWindow", "Continous-Wave mode"))
        self.radioButtonODMRPulse.setText(_translate("OdmactorMainWindow", "Pulse mode"))
        self.checkBoxODMRFrequencyScanning.setText(_translate("OdmactorMainWindow", "Scanning Frequency"))
        self.label_34.setText(_translate("OdmactorMainWindow", "Unit"))
        self.comboBoxODMRFrequencyUnit.setItemText(0, _translate("OdmactorMainWindow", "GHz"))
        self.comboBoxODMRFrequencyUnit.setItemText(1, _translate("OdmactorMainWindow", "MHz"))
        self.comboBoxODMRFrequencyUnit.setItemText(2, _translate("OdmactorMainWindow", "KHz"))
        self.comboBoxODMRFrequencyUnit.setItemText(3, _translate("OdmactorMainWindow", "Hz"))
        self.label_17.setText(_translate("OdmactorMainWindow", "Frequency start"))
        self.label_18.setText(_translate("OdmactorMainWindow", "Frequency end"))
        self.label_19.setText(_translate("OdmactorMainWindow", "Frequency step"))
        self.groupBoxODMRTime.setTitle(_translate("OdmactorMainWindow", "Time-domain Detecting"))
        self.groupBox_12.setTitle(_translate("OdmactorMainWindow", "Detecting Mode"))
        self.radioButtonODMRRabi.setText(_translate("OdmactorMainWindow", "Rabi"))
        self.radioButtonODMRRamsey.setText(_translate("OdmactorMainWindow", "Ramsey"))
        self.radioButtonPulseODMRRelaxation.setText(_translate("OdmactorMainWindow", "T1 relaxation"))
        self.checkBoxODMRTimeScanning.setText(_translate("OdmactorMainWindow", "Scanning Time"))
        self.label_32.setText(_translate("OdmactorMainWindow", "Unit"))
        self.comboBoxODMRTimeUnit.setItemText(0, _translate("OdmactorMainWindow", "s"))
        self.comboBoxODMRTimeUnit.setItemText(1, _translate("OdmactorMainWindow", "ms"))
        self.comboBoxODMRTimeUnit.setItemText(2, _translate("OdmactorMainWindow", "us"))
        self.comboBoxODMRTimeUnit.setItemText(3, _translate("OdmactorMainWindow", "ns"))
        self.label_30.setText(_translate("OdmactorMainWindow", "Time start"))
        self.label_31.setText(_translate("OdmactorMainWindow", "Time end"))
        self.label_33.setText(_translate("OdmactorMainWindow", "Time step"))
        self.label_35.setText(_translate("OdmactorMainWindow", "Interval length"))
        self.radioButtonODMRTimeUseStep.setText(_translate("OdmactorMainWindow", "Step mode"))
        self.radioButtonODMRTimeUseLength.setText(_translate("OdmactorMainWindow", "Length mode"))
        self.radioButtonODMRTimeUseLengthAndLogarithm.setText(_translate("OdmactorMainWindow", "Logarithm Length"))
        self.groupBoxODMRSequenceConfiguration.setTitle(_translate("OdmactorMainWindow", "Sequences Settings (Unit: ns)"))
        self.label_23.setText(_translate("OdmactorMainWindow", "Pre-readout interval"))
        self.checkBoxODMRMicrowaveOnOff.setText(_translate("OdmactorMainWindow", "With Microwave On/Off"))
        self.label_8.setText(_translate("OdmactorMainWindow", "Laser initialization"))
        self.label_22.setText(_translate("OdmactorMainWindow", "Signal readout"))
        self.label_20.setText(_translate("OdmactorMainWindow", "Period interval"))
        self.label_3.setText(_translate("OdmactorMainWindow", "Period Number"))
        self.label_6.setText(_translate("OdmactorMainWindow", "Microwave operation"))
        self.label_10.setText(_translate("OdmactorMainWindow", "Laser/Microwave interval"))
        self.label_24.setText(_translate("OdmactorMainWindow", "Microwave/Readout interval"))
        self.checkBoxODMRWithReference.setText(_translate("OdmactorMainWindow", "With Reference Signal"))
        self.label_21.setText(_translate("OdmactorMainWindow", "Sig/Ref readout interval"))
        self.label_5.setText(_translate("OdmactorMainWindow", "Lockin sync frequency"))
        self.spinBoxODMRSyncFrequency.setSuffix(_translate("OdmactorMainWindow", "Hz"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageODMR), _translate("OdmactorMainWindow", "ODMR Measurement"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pageSpin), _translate("OdmactorMainWindow", "Spin Manipulation"))
        self.groupBoxPhotonCountCongiuration.setTitle(_translate("OdmactorMainWindow", "Photon Detecting Configuration"))
        self.labelBinWidth.setText(_translate("OdmactorMainWindow", "Bin width"))
        self.comboBoxBinwidthUnit.setItemText(0, _translate("OdmactorMainWindow", "s"))
        self.comboBoxBinwidthUnit.setItemText(1, _translate("OdmactorMainWindow", "ms"))
        self.comboBoxBinwidthUnit.setItemText(2, _translate("OdmactorMainWindow", "us"))
        self.comboBoxBinwidthUnit.setItemText(3, _translate("OdmactorMainWindow", "ns"))
        self.comboBoxBinwidthUnit.setItemText(4, _translate("OdmactorMainWindow", "ps"))
        self.labelCountNumber.setText(_translate("OdmactorMainWindow", "Count number"))
        self.radioButtonPhotonCountRate.setText(_translate("OdmactorMainWindow", "Count rate"))
        self.groupBoxPhotonCountVisualization.setTitle(_translate("OdmactorMainWindow", "Real-time Counting"))
        self.groupBoxPhotonCountOperation.setTitle(_translate("OdmactorMainWindow", "Detecting Operation"))
        self.pushButtonPhotonCountOnOff.setText(_translate("OdmactorMainWindow", "On/Off"))
        self.pushButtonPhotonCountRefresh.setText(_translate("OdmactorMainWindow", "Refresh"))
        self.pushButtonPhotonCountSaveData.setText(_translate("OdmactorMainWindow", "Save data"))
        self.pushButtonTaggerConnect.setText(_translate("OdmactorMainWindow", "Connect tagger"))
        self.pushButtonTaggerClose.setText(_translate("OdmactorMainWindow", "Close tagger"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPhotonCount), _translate("OdmactorMainWindow", "Photon Count"))
        self.groupBoxSequenceVisualization.setTitle(_translate("OdmactorMainWindow", "Sequence Visualization"))
        self.groupBoxSequenceConfiguration.setTitle(_translate("OdmactorMainWindow", "Sequence Configuration (Unit: ns)"))
        item = self.tableWidgetSequence.verticalHeaderItem(0)
        item.setText(_translate("OdmactorMainWindow", "Channel 1"))
        item = self.tableWidgetSequence.verticalHeaderItem(1)
        item.setText(_translate("OdmactorMainWindow", "Channel 2"))
        item = self.tableWidgetSequence.verticalHeaderItem(2)
        item.setText(_translate("OdmactorMainWindow", "Channel 3"))
        item = self.tableWidgetSequence.verticalHeaderItem(3)
        item.setText(_translate("OdmactorMainWindow", "Channel 4"))
        item = self.tableWidgetSequence.verticalHeaderItem(4)
        item.setText(_translate("OdmactorMainWindow", "Channel 5"))
        item = self.tableWidgetSequence.verticalHeaderItem(5)
        item.setText(_translate("OdmactorMainWindow", "Channel 6"))
        item = self.tableWidgetSequence.verticalHeaderItem(6)
        item.setText(_translate("OdmactorMainWindow", "Channel 7"))
        item = self.tableWidgetSequence.verticalHeaderItem(7)
        item.setText(_translate("OdmactorMainWindow", "Channel 8"))
        item = self.tableWidgetSequence.horizontalHeaderItem(0)
        item.setText(_translate("OdmactorMainWindow", "High"))
        item = self.tableWidgetSequence.horizontalHeaderItem(1)
        item.setText(_translate("OdmactorMainWindow", "Low"))
        item = self.tableWidgetSequence.horizontalHeaderItem(2)
        item.setText(_translate("OdmactorMainWindow", "High"))
        item = self.tableWidgetSequence.horizontalHeaderItem(3)
        item.setText(_translate("OdmactorMainWindow", "Low"))
        item = self.tableWidgetSequence.horizontalHeaderItem(4)
        item.setText(_translate("OdmactorMainWindow", "High"))
        item = self.tableWidgetSequence.horizontalHeaderItem(5)
        item.setText(_translate("OdmactorMainWindow", "Low"))
        item = self.tableWidgetSequence.horizontalHeaderItem(6)
        item.setText(_translate("OdmactorMainWindow", "High"))
        item = self.tableWidgetSequence.horizontalHeaderItem(7)
        item.setText(_translate("OdmactorMainWindow", "Low"))
        item = self.tableWidgetSequence.horizontalHeaderItem(8)
        item.setText(_translate("OdmactorMainWindow", "High"))
        item = self.tableWidgetSequence.horizontalHeaderItem(9)
        item.setText(_translate("OdmactorMainWindow", "Low"))
        item = self.tableWidgetSequence.horizontalHeaderItem(10)
        item.setText(_translate("OdmactorMainWindow", "High"))
        item = self.tableWidgetSequence.horizontalHeaderItem(11)
        item.setText(_translate("OdmactorMainWindow", "Low"))
        item = self.tableWidgetSequence.horizontalHeaderItem(12)
        item.setText(_translate("OdmactorMainWindow", "High"))
        item = self.tableWidgetSequence.horizontalHeaderItem(13)
        item.setText(_translate("OdmactorMainWindow", "Low"))
        __sortingEnabled = self.tableWidgetSequence.isSortingEnabled()
        self.tableWidgetSequence.setSortingEnabled(False)
        self.tableWidgetSequence.setSortingEnabled(__sortingEnabled)
        self.groupBoxASGDevice.setTitle(_translate("OdmactorMainWindow", "Device"))
        self.pushButtonASGOpen.setText(_translate("OdmactorMainWindow", "Open"))
        self.pushButtonASGClose.setText(_translate("OdmactorMainWindow", "Close"))
        self.pushButtonASGStart.setText(_translate("OdmactorMainWindow", "Start"))
        self.pushButtonASGStop.setText(_translate("OdmactorMainWindow", "Stop"))
        self.groupBoxASGPulse.setTitle(_translate("OdmactorMainWindow", "Pulse"))
        self.pushButtonASGLoad.setText(_translate("OdmactorMainWindow", "Load"))
        self.pushButtonASGClear.setText(_translate("OdmactorMainWindow", "Clear"))
        self.pushButton_3.setText(_translate("OdmactorMainWindow", "PushButton"))
        self.pushButtonASGAdd.setText(_translate("OdmactorMainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabASGSequence), _translate("OdmactorMainWindow", "ASG Sequence"))
        self.groupBoxODMRFrequencyChartOperation.setTitle(_translate("OdmactorMainWindow", "Operation"))
        self.pushButtonODMRFrequencyInterrupt.setText(_translate("OdmactorMainWindow", "Interrupt"))
        self.pushButtonODMRFrequencySave.setText(_translate("OdmactorMainWindow", "Save"))
        self.radioButtonODMRFrequencyShowCount.setText(_translate("OdmactorMainWindow", "Show count"))
        self.pushButtonODMRFrequencyFit.setText(_translate("OdmactorMainWindow", "Fit"))
        self.pushButton_8.setText(_translate("OdmactorMainWindow", "(reserved)"))
        self.radioButtonODMRFrequencyShowContrast.setText(_translate("OdmactorMainWindow", "Show contrast"))
        self.groupBoxODMRFrequencyChart.setTitle(_translate("OdmactorMainWindow", "Frequency-domain ODMR Spectrum"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabODMRFrequency), _translate("OdmactorMainWindow", "Frequency-domain Detecting"))
        self.groupBoxODMRTimeChartOperation.setTitle(_translate("OdmactorMainWindow", "Operation"))
        self.pushButtonODMRTimeInterreupt.setText(_translate("OdmactorMainWindow", "Interrupt"))
        self.pushButtonODMRTimeSave.setText(_translate("OdmactorMainWindow", "Save"))
        self.pushButtonODMRTimeFit.setText(_translate("OdmactorMainWindow", "Fit"))
        self.pushButton_12.setText(_translate("OdmactorMainWindow", "(reserved)"))
        self.radioButtonODMRTimeShowCount.setText(_translate("OdmactorMainWindow", "Show count"))
        self.radioButtonODMRTimeShowContrast.setText(_translate("OdmactorMainWindow", "Show contrast"))
        self.groupBoxODMRTimeChart.setTitle(_translate("OdmactorMainWindow", "Time-domain Measurement Chart"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabODMRTime), _translate("OdmactorMainWindow", "Time-domain Detecting"))
        self.menuAbout_A.setTitle(_translate("OdmactorMainWindow", "About(&A)"))
        self.actionAbout.setText(_translate("OdmactorMainWindow", "About"))
        self.actionHelp.setText(_translate("OdmactorMainWindow", "Help"))
        self.actionQtInfo.setText(_translate("OdmactorMainWindow", "Qt Info"))

