# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui02.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(674, 440)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBoxReadOnly = QtWidgets.QCheckBox(Form)
        self.checkBoxReadOnly.setObjectName("checkBoxReadOnly")
        self.horizontalLayout_2.addWidget(self.checkBoxReadOnly)
        self.checkBoxEditable = QtWidgets.QCheckBox(Form)
        self.checkBoxEditable.setObjectName("checkBoxEditable")
        self.horizontalLayout_2.addWidget(self.checkBoxEditable)
        self.checkBoxClearContent = QtWidgets.QCheckBox(Form)
        self.checkBoxClearContent.setObjectName("checkBoxClearContent")
        self.horizontalLayout_2.addWidget(self.checkBoxClearContent)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonBold = QtWidgets.QPushButton(Form)
        self.pushButtonBold.setCheckable(True)
        self.pushButtonBold.setObjectName("pushButtonBold")
        self.horizontalLayout_3.addWidget(self.pushButtonBold)
        self.pushButtonItalic = QtWidgets.QPushButton(Form)
        self.pushButtonItalic.setCheckable(True)
        self.pushButtonItalic.setObjectName("pushButtonItalic")
        self.horizontalLayout_3.addWidget(self.pushButtonItalic)
        self.pushButtonUnderline = QtWidgets.QPushButton(Form)
        self.pushButtonUnderline.setCheckable(True)
        self.pushButtonUnderline.setObjectName("pushButtonUnderline")
        self.horizontalLayout_3.addWidget(self.pushButtonUnderline)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonLeft = QtWidgets.QPushButton(Form)
        self.pushButtonLeft.setCheckable(True)
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.horizontalLayout.addWidget(self.pushButtonLeft)
        self.pushButtonCenter = QtWidgets.QPushButton(Form)
        self.pushButtonCenter.setCheckable(True)
        self.pushButtonCenter.setChecked(True)
        self.pushButtonCenter.setObjectName("pushButtonCenter")
        self.horizontalLayout.addWidget(self.pushButtonCenter)
        self.pushButtonRight = QtWidgets.QPushButton(Form)
        self.pushButtonRight.setCheckable(True)
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.horizontalLayout.addWidget(self.pushButtonRight)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBoxReadOnly.setText(_translate("Form", "ReadOnly"))
        self.checkBoxEditable.setText(_translate("Form", "Editable"))
        self.checkBoxClearContent.setText(_translate("Form", "ClearContent"))
        self.lineEdit.setText(_translate("Form", "测试显示文本"))
        self.pushButtonBold.setText(_translate("Form", "粗体"))
        self.pushButtonItalic.setText(_translate("Form", "斜体"))
        self.pushButtonUnderline.setText(_translate("Form", "下划线"))
        self.pushButtonLeft.setText(_translate("Form", "左对齐"))
        self.pushButtonCenter.setText(_translate("Form", "居中"))
        self.pushButtonRight.setText(_translate("Form", "右对齐"))
